// Generated by IcedCoffeeScript 1.4.0b
(function() {
  var terminals;

  terminals = function(s) {
    var c, current_terminal, last_paren_type, output, tag, terminal, to_print, _i, _len, _ref;
    output = [];
    current_terminal = [];
    for (_i = 0, _len = s.length; _i < _len; _i++) {
      c = s[_i];
      if (c === '(') {
        last_paren_type = '(';
        current_terminal = [];
      } else if (c === ')') {
        if (last_paren_type === '(') {
          if (current_terminal.length > 0) {
            to_print = current_terminal.join('');
            _ref = to_print.split(' '), tag = _ref[0], terminal = _ref[1];
            output.push(terminal);
          }
        }
        last_paren_type = ')';
        current_terminal = [];
      } else {
        current_terminal.push(c);
      }
    }
    return output.join('');
  };

  console.log(terminals('( (IP (NP (PN 你们)) (VP (VV 好像) (VP (VV 不想) (IP (VP (VV 学习)))))) )'));

}).call(this);
